title: Zhiq'Log
author: Zhiqiang Wang
address: Beijing, China
email: zhiqwang@outlook.com

# Short description of your site
description: > # this means to ignore newlines until "show_exerpts:"
  I wanna to discribe and solve question through mathematics and coding...
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: zhiqwang
    linkedin: zhiqiangwang
    twitter: zhikwang
    rss: RSS

disqus:
  shortname: zhiqwang

google_analytics: UA-138093514-1

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - tags.html
  - about.html

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
